### ISSUE TITLE
AttributeError: Can't pickle local object 'make_env.<locals>._make_env'

### ISSUE THREAD

**Issue by lucifer2859** [tristandeleu/pytorch-maml-rl#51]
Ubuntu 18.04.5 LTS
Meet this problem after adding 'mp.set_start_method('spawn')'
https://github.com/tristandeleu/pytorch-maml-rl/issues/40#issuecomment-632598191

Traceback (most recent call last):
  File "train.py", line 122, in <module>
    main(args)
  File "train.py", line 54, in main
    num_workers=args.num_workers)
  File "/home/dchen/pytorch-maml-rl/maml_rl/samplers/multi_task_sampler.py", line 107, in __init__
    worker.start()
  File "/home/dchen/anaconda3/envs/torch/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/dchen/anaconda3/envs/torch/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/dchen/anaconda3/envs/torch/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/dchen/anaconda3/envs/torch/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/dchen/anaconda3/envs/torch/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/dchen/anaconda3/envs/torch/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/dchen/anaconda3/envs/torch/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'make_env.<locals>._make_env'

**Comment by lucifer2859** [comment]
I see the similar problem in https://github.com/tristandeleu/pytorch-maml-rl/issues/41

**Comment by tristandeleu** [comment]
I am able to replicate this issue using `mp.set_start_method('spawn')`. Can you try the [fix/mp-spawn](https://github.com/tristandeleu/pytorch-maml-rl/tree/fix/mp-spawn) branch, see if that fixes your issue?
I'm having trouble understanding why this doesn't work though. I know that objects that are passed as arguments to a process are pickled, and local functions generally don't work well with pickle, but here that function is not passed as an argument, but is instead called inside the process (and therefore shouldn't need to be pickled?).

**Comment by lucifer2859** [comment]
Thanks a lot. After adding 'mp.set_start_method('spawn')', I fix this problem using this branch https://github.com/tristandeleu/pytorch-maml-rl/tree/fix/mp-spawn

**Comment by TriumphLearning** [comment]
> Thanks a lot. After adding 'mp.set_start_method('spawn')', I fix this problem using this branch https://github.com/tristandeleu/pytorch-maml-rl/tree/fix/mp-spawn

Hello, I have same problem with you，and I just wonder where 'mp.set_start_method('spawn')'  should be placed in that position in the branch https://github.com/tristandeleu/pytorch-maml-rl/tree/fix/mp-spawn ?
Thank you very much
